version: 2.1
jobs:
  build:
    working_directory: ~/sunbird-pdf-player
    docker:
      - image: circleci/node:12.20.2-browsers
    steps:
      - checkout:
          path: ~/sunbird-pdf-player
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          environment:
            NG_CLI_ANALYTICS: "ci"
          command: npm install
      - run: cd projects/sunbird-pdf-player && sudo npm install
      - run:
          name: Node install
          command: sudo npm install
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Testing
          command: npm run test
      - run:
          name: Install sonar scanner
          command: 'sudo npm install -i -g sonarqube-scanner'
      - run:
          name: Sonar scanner
          command: cd ~/sunbird-pdf-player && sonar-scanner
      - run:
          name: Publish to NPM
          command: |
            if [ -z $CIRCLE_PR_NUMBER ]; then
              npm run build-lib && npm pack ./dist/sunbird-pdf-player
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
              npm publish project-sunbird-sunbird-pdf-player-v9-*
            else
              npm run build-lib && npm pack ./dist/sunbird-pdf-player
            fi
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
